### ISSUE TITLE
Enable landscaper-cli installation via homebrew

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/landscapercli#115]
Since we have a homebrew tap (https://github.com/gardener/homebrew-tap), we should add the landscaper CLI to it (unless this causes problems which I'm currently not aware of).
This will make it easier to install and update the CLI.

**Comment by In-Ko** [comment]
Move to new backlog, prio 4.

**Comment by In-Ko** [comment]
Closed, as moved to new backlog.
