### ISSUE TITLE
Render blueprint fails when resources of the local component descriptor are referenced

### ISSUE THREAD

**Issue by achimweigel** [gardener/landscapercli#116]
**Description**

The render blueprint command fails when the blueprint contains a reference to a json schema stored in the local component descriptor. Similar problems will occur if other local resources of the component descriptor are referenced.

**Done Criteria**
- [x] All Features implemented
- [x] Code has been reviewed by other team members
- [x] Unit Tests created for new code
- [x] Integration Test Suite updated (if applicable)
- [x] Internal technical Documentation updated
- [x] Enduser Documentation updated (if applicable)
- [x] Successful demonstration in Review

**Comment by robertgraeff** [comment]
Feature requires code changes in Landscaper and Landscaper CLI.
- Changes in Landscaper are done (PR merged);
- Changes in Landscaper CLI require a new Landscaper release and then an update of the Landscaper version in the CLI.

Functionality:
- DONE: Validation against schema in own component descriptor
- DONE: Go templating of deploy items with resource from component descriptor
- OPEN: Spiff templating of deploy items with resource from component descriptor

**Comment by In-Ko** [comment]
Closed already in January, so closing this one.
