### ISSUE TITLE
Automatic import creation

### ISSUE THREAD

**Issue by achimweigel** [gardener/landscapercli#117]
**What would you like to be added**:

I a blueprint has complex import or export data it might be useful to render these automatically from golang types. An example implementation could be found here: https://github.com/gardener/gardener/pull/5276. 

In a first step the json schema are created and provided in go function. In the next step, the import section of the blueprint is created and the json schema files added to the blueprint as local files.

**Why is this needed**:

**Comment by In-Ko** [comment]
Move to new backlog, with prio 4.

**Comment by In-Ko** [comment]
Closing, as moved to new backlog.
