### ISSUE TITLE
render of blueprint fails when referenced component is not available locally

### ISSUE THREAD

**Issue by reshnm** [gardener/landscapercli#121]
**What happened**:

When rendering a blueprint of component `A`  that accesses a ressource of component reference `B` the rendering fails when component `B` is not available locally. Assuming component `B` is stored in an OCI repository which can be accessed with a repository context specifyied in component `A`.

This fails:

 `landscaper-cli blueprints render ./blueprint all -f ./values-render.yaml -c ./component-descriptor-A.yaml`

`unable to template deploy executions: template: execution:27:42: executing "execution" at <getComponent .cd "name" "B">: error calling getComponent: unable to resolve component B:v0.1.0`

This works:

`landscaper-cli blueprints render ./blueprint all -f ./values-render.yaml -c ./component-descriptor-A.yaml -a ./component-descriptor-B.yaml `

**What you expected to happen**:

landscaper-cli should be able to resolve referenced components in an OCI registry.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

landscaper-cli v0.13.0

**Comment by In-Ko** [comment]
Closing here, as moved to new backlog project.
