### ISSUE TITLE
Integrate commands of component-cli

### ISSUE THREAD

**Issue by achimweigel** [gardener/landscapercli#13]
Commands of the [component-cli](https://github.com/gardener/component-cli) should be integrated. This includes the removal and redirection of component-cli commands now implemented there.

**Done Criteria**
- [x] All Features implemented
- [x] Code has been reviewed by other team members
- [x] Unit Tests created for new code
- [ ] Integration Test Suite updated (if applicable)
- [ ] Internal technical Documentation updated
- [x] Enduser Documentation updated (if applicable)
- [x] Successful demonstration in Review

**Comment by In-Ko** [comment]
The components-cli is integrated "as-is" into the landscaper-cli (and the old component-cli commands have been deleted form the landscaper-cli) => Closing this issue.
