### ISSUE TITLE
Cannot upload blueprints and components

### ISSUE THREAD

**Issue by dav9** [gardener/landscapercli#19]
I'm using Harbor as an OCI repository, I've added my user, password, registry under these env vars: ${OCI_USER}, ${OCI_PASS} and ${OCI_REPO}. ${REPO} is a harbor project that I've created for artefacts. I have done docker login -u ${OCI_USER} -p ${OCI_PASS} ${OCI_REPO}.

Both blueprint and component push produce authentication errors. I'm using the OSX keyring

landscaper-cli blueprints push \
		${OCI_REPO}/${REPO}/blueprints/&lt;blueprint name&gt;:${VERSION} blueprints/service-a

I get error: authentication for ${REPO} cannot be found :

Level(-10)      ociKeyring      added authentication for "${REPO}" from default docker config
Level(-10)      ociKeyring      added authentication for "https://index.docker.io/v1/" from default docker config
authentication for ${REPO} cannot be found

landscaper-cli components-cli component-archive remote push \
	components/service-a

Level(-10)      added authentication for "${REPO}" from default docker config
Level(-10)      added authentication for "https://index.docker.io/v1/" from default docker config
authentication for $REPO cannot be found

I've debugged a bit - the structure from dockerconfig is empty.

**Comment by In-Ko** [comment]
FYI @achimweigel @schrodit

**Comment by schrodit** [comment]
the previous version of the component-cli was unable to use the osc native credential store.
With that update it should be possible: https://github.com/gardener/landscapercli/pull/17

**Comment by dav9** [comment]
@schrodit - does the blueprint push command share the code from the https://github.com/gardener/component-cli/pull/2?

**Comment by dav9** [comment]
https://github.com/gardener/landscapercli/pull/17 fixes the issue.
