### ISSUE TITLE
Command "landscaper installation create / deploy"

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#21]
**Description**
After a user has used `landscaper quickstart` , followed by `landscaper component create ...` , there needs to be a command which creates a working skeleton for an installation.yaml, which could then be applied to a cluster using `kubectl apply`.
Main task here to be solved is how the import parameters as defined in a blueprint can be fulfilled as automated as possible. The same is true for the export parameters, so that the user can make sure that the exports are filled with data as defined in the blueprint.

**Done Criteria**
- [x] All Features implemented
- [x] Code has been reviewed by other team members
- [x] Unit Tests created for new code
- [x] Integration Test Suite updated (if applicable)
- [ ] Internal technical Documentation updated
- [x] Enduser Documentation updated (if applicable)
- [x] Successful demonstration in Review

**Comment by enrico-kaack-comp** [comment]
Update:
- [x] "landscaper-cli installation create ..." command to create an installation from a cd generates an installation yaml with imports/exports and type annotations as comments.
- [ ] for basic datatypes, we will implement a  "landscaper-cli installation set-input-params --param-key1=param-value1 ..." to set import parameters to hardcoded values (as importDataMappings) in the yaml file
- [ ] we will implement a "landscaper-cli target create ..." command to create a target from a kubeconfig and apply it to the server

**Comment by In-Ko** [comment]
Status after Sprint 1b:
- Implementation for both `installation create`, `target create` and  `installation set-input-params` finished

Leftovers:
- Fix for the Quote-Bug, where passing a string in quotes does lead to problems in the `set-input-params`command.
- Update Integration Test Suite with a Test covering all new commands mentioned above. Desired scope of the test: Generation of a valid & usable installation.yaml, including generation of needed import parameters. The test has to be as close as possible to a "real world installation.yaml deployment", even though the actual deployment will be a rather small one, like an NGINX deployment for example.
- After those two leftovers are done, the whole backlog item can be regarded as done.

**Comment by enrico-kaack-comp** [comment]
Update: 
- [x] Quote Bug fixed
- [x] Added -o parameter to make output more intuitive #42 

- [ ] integration tests
- [ ] resolve the json schema if it contains a nested schema reference

**Comment by In-Ko** [comment]
Current ToDos:
- Check what happens in case there are cyclic dependencies between referenced types and how to resolve those
- Setup Integration Tests. For this, we have to clarify with Tim how they perform tests using an OCI Registry (public one ?), as doing this with a "localhost" OCI Registry makes it very complicated and hard to maintain, and it is not resembling a real scenario, where a central OCI Registry is always used.

**Comment by achimweigel** [comment]
Documentation with example can be found here: https://github.com/gardener/landscapercli/blob/master/docs/commands/container_deployer/add_container_di.md

**Comment by In-Ko** [comment]
@achimweigel: I guess the above comment should rather be located in #37 , no ?

**Comment by achimweigel** [comment]
yes :-)

**Comment by In-Ko** [comment]
- All done (checking for cyclic dependencies & setting up integration tests)
