### ISSUE TITLE
Update CLI Build Pipeline

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#23]
**Description**
In order to ensure best possible quality for the landscaper cli, we have to update the pipeline in such a way that it runs the CLI Test Suite, and only creates a new Release of the CLI if all Tests run through completely.
If a test fails, the pipeline must report the failing test (as usual, see Potter pipelines ...) in a human readable protocol, so that it is easy to identify the problem.

- also execute "make generate" to update the documentation
- And also update the version.Info (see the task #24 )

**Done Criteria**
- [x] All Features implemented
- [x] Code has been reviewed by other team members
- [x] Unit Tests created for new code
- [ ] Integration Test Suite updated (if applicable)
- [x] Internal technical Documentation updated
- [ ] Enduser Documentation updated (if applicable)
- [x] Successful demonstration in Review

**Comment by guewa** [comment]
master-release-job with integration-tests
https://concourse.ci.gardener.cloud/teams/gardener/pipelines/landscaper-cli-master/jobs/master-release-job

**Comment by In-Ko** [comment]
Status after Sprint 1b:
- Integration Test Suite integrated in build pipeline

Leftovers:
- Integration Test Suite should run every 2 hrs for Dev
- Integration Test Suite should run "on pull-request".
  - This needs to be thought through, as tests must not compete with each other if they run in parallel.
- Pipeline has to perform a `make generate` command to update the documentation of the CLI.

**Comment by guewa** [comment]
- [ ] Integration Test Suite should run every 2 hrs for Dev
https://concourse.ci.gardener.cloud/teams/gardener/pipelines/landscaper-cli-master/jobs/master-integration-test-job
- [ ] Pipeline has to perform a `make generate` command to update the documentation of the CLI. 
added to .ci/verify script, which is called in every pipeline job
Example of failing job https://concourse.ci.gardener.cloud/teams/gardener/pipelines/landscaper-cli-master/jobs/master-head-update-job/builds/85

- [ ] Integration Test Suite should run "on pull-request".
  - This needs to be thought through, as tests must not compete with each other if they run in parallel.

**Comment by guewa** [comment]
Integration Tests now suppresses parallel execution and have their own clusters:
- 2h cron job: int-test-cron
- Pull Request: int-test-pr
- Release: int-test
This ensures that the needed installation/deinstallation of the landscaper doesn't mess with each other

**Comment by In-Ko** [comment]
This is done for now.
