### ISSUE TITLE
"landscaper-cli blueprint add helm-ls value" command is outdated in the documentation

### ISSUE THREAD

**Issue by ivanspasov99** [gardener/landscapercli#27]
Command (`landscaper-cli blueprint add helm-ls value`) option `[execution name]` is not available anymore. It is not updated in the following documentation.

File: https://github.com/gardener/landscapercli/blob/master/docs/drafts/scenarios/01-create-blueprint-with-helm-charts/commands.md#step-3-add-fixed-values-for-helm-templating

Command options from documentation:

![Screenshot 2021-02-02 at 12 32 57](https://user-images.githubusercontent.com/23458270/106587869-cf9f9d80-6552-11eb-9adf-a8a234ee7fea.png)

Command options from the CLI tool:

![Screenshot 2021-02-02 at 12 30 11](https://user-images.githubusercontent.com/23458270/106587769-b26acf00-6552-11eb-8c00-0da0c4d0e0d9.png)

**Comment by In-Ko** [comment]
Thanks for letting us know! We will look into this. We are aware that currently, things are moving pretty fast in our and the related projects, so there might be times when the documentation does not reflect the current state of the CLI. We will try to minimize such situations of course.

**Comment by achimweigel** [comment]
This is part of the draft section and no official documentation. I guess we need something for work in progress.

**Comment by achimweigel** [comment]
We have removed the draft section to not confuse others.
