### ISSUE TITLE
Include Windows executable in release assets

### ISSUE THREAD

**Issue by ivanchuchulski** [gardener/landscapercli#298]
**What would you like to be added**:
per-build executable for Windows AMD64 architecture in a version release
**Why is this needed**:
Ease of installation and usage

Hello, I'd like to ask how can I install landscaper-cli on a Windows 11 machine with amd64 architecture? 

Do I have to build it somehow from source code? I can't see an executable artifact to download in the "Releases page". 

For example, other Gardener tools, like `gardenlogin` have and windows amd64 executable in their releases, e.g. https://github.com/gardener/gardenlogin/releases/tag/v0.5.1 (see _gardenlogin_windows_amd64.exe_). 
Thanks in advance!

**Comment by robertgraeff** [comment]
Hi Ivan,

we have added the build of a windows executable.

Solved with #300

**Comment by ivanchuchulski** [comment]
Hello, 

Thank you very much for the quick response! 

I'd just kindly ask for one more thing, if it would be possible to name the artifact in the `gz` archive to be with .exe extension, in order to make it execute directly in PowerShell. 

And another thing, maybe I'm missing something, but the only way I could make the completion work, was to rename the executable with a dash like so: `landscaper-cli.exe`, like it's mentioned in the README installation instructions of the project. Naming it `landscapercli.exe` only, wouldn't work. 

Thanks in advance!
