### ISSUE TITLE
Add Container Deployer Support for "component create" CLI command

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#37]
**Description**
Similar to the existing support of the `helm-ls` and `manifest` deployer, the CLI must also support the `container deployer`. So similar to the other deployers, it should be possible to add a container-based deployment via the CLI to a component.
This is crucial for some of the Gardener-Components.

**Done Criteria**
- [x] All Features implemented
- [x] Code has been reviewed by other team members
- [x] Unit Tests created for new code
- [x] Integration Test Suite updated (if applicable)
- [ ] Internal technical Documentation updated
- [x] Enduser Documentation updated (if applicable)
- [ ] Successful demonstration in Review

**Comment by achimweigel** [comment]
- basic functionality implemented and documented
- missing
  - integration tests
  - handling of image pull secrets
  - description/example for data in blueprint, blueprint and component descriptor reference in deploy item
  - adapt description of component deployed in landscaper project

**Comment by In-Ko** [comment]
Current State: See above comment

**Comment by In-Ko** [comment]
So all the missing work mentioned above is done ?
- [ ] integration tests
- [ ] handling of image pull secrets
- [ ] description/example for data in blueprint, blueprint and component descriptor reference in deploy item
- [ ] adapt description of container deployer in landscaper project

**Comment by achimweigel** [comment]
Sure. That's the reason why I marked all done criteria accordingly :-)

**Comment by In-Ko** [comment]
- Remaining docu for the CLI & for the container deployer in the landscaper docu has been created and tested
- Unit tests & Integration tests have been created
