### ISSUE TITLE
Check Container Deployer Documentation and execute examples

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#49]
**Description**
We need to verify the documentation regarding the Container Deployer in both the landscaper-cli and landscaper repositories. In order to do this, we also need to execute the corresponding examples.
Feedback reg. the documentations and the examples should be gathered and presented to the team, so that we can update the documentation / examples accordingly.
This task is also very helpful to onboard colleagues to the overal landscaper / landscaper-cli topic.

**Done Criteria**
- [x] Container Deployer Documentation verified
- [ ] Feedback gathered and presented to the team(s)
- [x] Documentation updated accordingly

**Comment by achimweigel** [comment]
Documentation with example can be found here: https://github.com/gardener/landscapercli/blob/master/docs/commands/container_deployer/add_container_di.md

**Comment by In-Ko** [comment]
I don't consider this done, as we discussed in the last sprint and also mentioned above as Done Criteria, that this task could be used to get new colleagues into the whole landscaper / landscaper-CLI topic by
- reading the container deployer documentation
- executing the corresponding examples and
- providing feedback

**Comment by In-Ko** [comment]
Close, as this is finished.
