### ISSUE TITLE
Include setup of the "quickstart" OCI registry ingress " in the "quickstart install" command

### ISSUE THREAD

**Issue by jschicktanz** [gardener/landscapercli#54]
**What would you like to be added**:
Include the setup of the ingress for the OCI registry of "landscaper-cli quickstart install" in the "install" command itself.

**Why is this needed**:
Currently when using "landscaper-cli quickstart install" to setup a Landscaper instance and an OCI registry in a shoot cluster, an ingress for accessing the registry without port-forwarding via localhost must be manually added via "landscaper-cli quickstart add-oci-endpoint". In reality this turned out to be a somewhat of a hassle (e.g. configuring the Landscaper instance with the correct registry credentials). These manual steps should be included in the "quickstart install" command itself. It should really take only 1 single command to get up and running with component development using the setup provided by the "quickstart" command.

**Comment by In-Ko** [comment]
Will the old command "landscaper-cli quickstart add-oci-endpoint" still be available or has it been included in the quickstart command itself ? If the latter, then the CLI Documentation needs to be adjusted accordingly (https://github.com/gardener/landscapercli/tree/master/docs/commands and subsequent pages ...)

**Comment by jschicktanz** [comment]
I directly included the logic in the "quickstart install" itself, therefore removing the "quickstart add-oci-endpoint" command. This has already been updated in the docs https://github.com/gardener/landscapercli/blob/master/docs/commands/quickstart/install.md#installing-and-configuring-the-oci-registry
