### ISSUE TITLE
Knowledge Build-up 'Landscaper' & 'Landscaper-CLI'

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#60]
**Description**
Some colleagues in the team still need to spend time to get confident with the Landscaper and Landscaper-CLI. This task here should reserve some time to
- Go through the landscaper and landscaper cli documentation
- Execute the examples as described in the documentation
- Provide feedback on the documentation and the examples

**Comment by achimweigel** [comment]
@In-Ko should we close this?

**Comment by In-Ko** [comment]
Hi, sure, will do so. Again one of these issues where we moved it to "closed" on the board, but the issue itself we left untouched :) ...
