### ISSUE TITLE
Create Landscaper Component for "Virtual Garden Cluster"

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#63]
**Description**
Create a landscaper-conform model for the Virtual Garden Cluster Component. The model should go along with a suitable documentation about how the model is structured, including its integration into the landscape-setup.

**Done Criteria**
- [ ] A model for the Virtual Garden Cluster has been created
- [ ] Documentation about the model has been created
- [ ] In landscape-setup, the new model is used

**Comment by achimweigel** [comment]
Questions

- Where is the component descriptor currently build containing the images used in the virtual garden chart

**Comment by robertgraeff** [comment]
Current [pull requests](https://github.com/gardener/virtual-garden/pulls) under review:
- Deployment of HVPA CRD
- Deployment of secrets with certificates

**Comment by achimweigel** [comment]
Current [pull requests](https://github.com/gardener/virtual-garden/pulls) under review:

- Deployment of secrets with certificates

**Comment by In-Ko** [comment]
set to blocked for now, we will pick this up again after Daniel has finished his component and we had another sync with him. Then we have to update the component due to the various changes ...

**Comment by achimweigel** [comment]
@In-Ko should we close this?

**Comment by In-Ko** [comment]
Yes.
