### ISSUE TITLE
Create Landscaper Component for "dns-external" gardener-extension

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#64]
**Description**
Create a landscaper-conform model for the "dns-external" Gardener Extension Component. The model should go along with a suitable documentation about how the model is structured, including its integration into the landscape-setup.

**Done Criteria**
- [ ] A model for the "dns-external" Gardener extension has been created
- [ ] Documentation about the model has been created
- [ ] In landscape-setup, the new model is used

**Comment by enrico-kaack-comp** [comment]
DONE Coding
PR Open needs to be merged

**Comment by guewa** [comment]
- [ ] after release, integration into landscape setup

**Comment by robertgraeff** [comment]
The Landscaper based deployment was activated with [PR "Enable landscaper based deployment for component dns-external" #2989](https://github.wdf.sap.corp/kubernetes/landscape-setup/pull/2989) 

The Landscaper based deployment for this component is therefore used on all landscapes where Landscaper is enabled in the landscape.yaml. Currently, this is dev.

**Comment by achimweigel** [comment]
@In-Ko should we close this?

**Comment by In-Ko** [comment]
Yes
