### ISSUE TITLE
Create Landscaper Component for "provider-aws" gardener-extension

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#65]
**Description**
Create a landscaper-conform model for the "provider-aws" Gardener Extension Component. The model should go along with a suitable documentation about how the model is structured, including its integration into the landscape-setup.

**Done Criteria**
- [x] A model for the "provider-aws" Gardener extension has been created
- [x] Documentation about the model has been created
- [ ] In landscape-setup, the new model is used

**Comment by achimweigel** [comment]
Todos

- Merge pull requests
   - https://github.com/gardener/gardener-extension-provider-aws/pull/327
   - https://github.wdf.sap.corp/kubernetes/landscape-setup/pull/2618
   - https://github.wdf.sap.corp/kubernetes-dev/landscape-dev-garden/pull/2478

- Integrate deployment of installation in deploy script in landscape setup such that new installation is used if landscaper enabled in landscape.yaml

- Prerequisits: 
  - new component-cli allowing more than one helm chart in a folder available
  - transport of local resources in component descriptor available

**Comment by achimweigel** [comment]
Status:
- Last PR for component merged. 
- Need to wait for next release of AWS extension to continue with integration

**Comment by In-Ko** [comment]
As discussed, we will use the AWS Component to verify the required concept to execute some kind of Code in Blueprints _before_ the concrete deployment (in this case Helm) takes place, and also _after_ the deployment ("Pre- and Afterburner").
Additionally, during this task we will create a library which calculates the machine images.

**Comment by In-Ko** [comment]
- We are currently not working actively on this component anymore
- The things discussed in the Gardener Workshop have been implemented as discussed
- Need to wait until the official "driver" in the Gardener Team has started working on this

**Comment by achimweigel** [comment]
@In-Ko should we close this?

**Comment by In-Ko** [comment]
Yes
