### ISSUE TITLE
Setup of central Landscaper Instances (per Landscape)

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#69]
**Description**
In order to test the installations/deployments of new Gardener Landscaper/CNUDIE Components, central Landscaper Instances are needed per Landscape (DEV, STAGING, ...). For now focus on the existing Landscapes, mainly to test the new Gardener Components and integrate them into the test machinery, later we also need to think about how to do the initial deployment of a landscaper for new landscapes.
Such central landscaper instances are also valuable for (upcoming) stakeholders of the landscaper.

**Done Criteria**
- [ ] A Landscaper is running on the Gardener DEV Landscape
- [ ] A Landscaper is running on the Gardener STAGING Landscape
- [ ] A Landscaper is running on the Gardener CANARY Landscape
- [ ] A Landscaper is running on the Gardener LIVE Landscape

**Comment by robertgraeff** [comment]
# To Do
- The landscaper config should contain the access data for a default OCI registry.

**Comment by In-Ko** [comment]
@achimweigel & @robertgraeff : Please update the ToDo List above and work on it.

**Comment by achimweigel** [comment]
todo list was updated
