### ISSUE TITLE
CLI Command "landscaper create"

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#7]
**Description**
Implement a CLI Command, which creates an example blueprint and component descriptor and the necessary directory structure locally, and additionally allows to push artefacts to an OCI Registry, using the component-cli.
It could work somehow similar to a [`helm create`](https://helm.sh/docs/helm/helm_create/)

**Done Criteria**
- [x] All Features implemented
- [x] Code has been reviewed by other team members
- [x] Unit Tests created for new code
- [x] Integration Test Suite updated (if applicable)
- [ ] Internal technical Documentation updated
- [x] Enduser Documentation updated (if applicable)
- [x] Successful demonstration in Review

**Comment by In-Ko** [comment]
As discussed, the following things should be added:
- Enable also a "Kubernetes Manifest Deployment" to this command. So similar to adding Helm Charts to a blueprint, it should be possible to also add manifest deployments to a blueprint.
- Add parameter-names to all parameters which have to be specified for a command. This makes it easier to read the full command.
- Finish / update documentation

**Comment by achimweigel** [comment]
- Add "Kubernetes Manifest Deployment" implemented
- positional arguments switched to flags except for name and version

**Comment by robertgraeff** [comment]
To discuss: 

* if one adds a deploy item with a local helm chart, one must currently specify the parent folder of the helm chart folder. Should we change the command so that the user has to specify the helm chart directory?

* Update flag at the add deploy item command

* Remove deploy item command

* Download component command

**Comment by In-Ko** [comment]
Status after 1b:
- Implementation and tests finished for "component create" with scope to support helm-ls and manifest deployer.
- Scope as described in this backlog item has been implemented and integrated into our test suite.
(Suggested Proposals from above (thanks @robertgraeff !) and other topics for the overall "component command chain" will be added as separate tasks to the backlog, as this makes tracking easier than extending the scope of this backlog item.
