### ISSUE TITLE
Enable "Copying of local resources" to LSSD

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#70]
**Description**
The LSSD (Landscape Setup Dependencies) at the moment does not support the copying of local resources. This needs to be added.

**Comment by enrico-kaack-comp** [comment]
- DONE added function to cc-utils to copy an oci artifact with its blobs
- PR OPEN use this function to replace the previous copying mechanism 
- IN PROGRESS also copy resources with access.type OciRegistry (currently, only resource.type oci image is copied)
