### ISSUE TITLE
CLI Command(s) for debugging

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#8]
**Description**
Implement a set of CLI Commands which help endusers to debug issues / find errors within a set of data objects / targets and sub installations. Those commands should be able to identify (and output) erroneous objects within a deployment, e.g. it should display the failing deploy item, including the complete path to this deploy item.
This should especially work for scenarios where component B depends on some exported data object from a deployment of component A (where component A is not owned by component B owner). At least the error should indicate that deployment B does not work because the data object to be imported is not available / in error state.
Additionally, there should be a command which visualises a complete dependency tree of a deployment.

**Done Criteria**
- [x] All Features implemented
- [ ] Code has been reviewed by other team members
- [x] Unit Tests created for new code
- [x] Integration Test Suite updated (if applicable)
- [x] Internal technical Documentation updated
- [ ] Enduser Documentation updated (if applicable)
- [x] Successful demonstration in Review

**Comment by In-Ko** [comment]
We discussed this again, and a first version of such debugging commands should be able to
- Display an "Artefacts Path" for a component descriptor (e.g. cp => blueprint(s) => installation(s) =>DeployItems)
- - Display an "Artefacts Path" for a component descriptor, highlighting a failing DeployItem

**Comment by enrico-kaack-comp** [comment]
The following concept has been discussed in the team and will be implemented:

**User Story**: The user wants to know wether an applied installation succeeded or why it failed. 
Right now, the information is distributed over multiple cr on the cluster. This command basically collects all information and represents it in a useful way.

**Possible command**:
`landscaper-cli debug status --name my-installation`

Example Output:
```[failed] inst my-installation
├── [successful] exec my-execution-1
│   ├── [✅] di deploy-item1
│   └── [✅] di deploy-item2
├── [failed] exec my-execution-2
│   └── [failed] di3
        lastError:
            lastTransitionTime: "2021-02-23T10:40:02Z"
            lastUpdateTime: "2021-02-23T10:40:09Z"
            message: '(Inst echo-server).cluster: unable to get target for ''cluster'': Target.landscaper.gardener.cloud "test-target2" not found'
            operation: ImportsSatisfied
            reason: unable to check that all imports are satisfied
└── [🚧] exec my-execution-3
    └── [🚧] di di4
```

Feedback/Notes:
- provide a flag to only show failed parts
- verbose mode: to show a very verbose but possibly confusing output for maximum details
- output format specification: allows to output the data in a fixed format to be machine readable (like -oyaml, -ojson)
- print the name of the cr in the tree to make it simple to use a kubectl describe on the object. This feature may be enabled/disabled with a flag.

**Comment by enrico-kaack-comp** [comment]
Feedback Landscaper friends:
- no need to show the execution as extra level since all errors are automatically propagated to the next higher level, could be moved to the verbose mode
- show semantic and logic name in the tree
- show all installations in a given namespace if no installation name is provided

**Comment by loewenstein** [comment]
I wouldn't use `debug`	as the sub-command. It is "just" displaying the status of an `Installation` in a comprehensive and detailed manner, right?

**Comment by In-Ko** [comment]
Thanks @loewenstein for your feedback. You are right, it is of course not a real "debugging" that is going on here, but an easy way to identify problematic deployitems (and the full path to those). We will discuss the name of the command again internally.

**Comment by enrico-kaack-comp** [comment]
suggestions: 
```
landscaper-cli installation status <installation-name>
landscaper-cli installation inspect <installation-name>

```

**Comment by In-Ko** [comment]
Current State:
- Command is now called "installations inspect"
- Execution objects can be switched on if needed (per default they are not shown)
- Shows all available installations if no specific is mentioned in the command
- Also features a detail-mode, displaying the whole yamls
- Filter for "failed" installations

Open:
- Bit more work on Unit Tests needed (using the "fake client" of the landscaper, to not have to use a real cluster)
- Minor update for the --help needed (explaining what happens if all options are ommited)
- Icons are not shown when using on conjunction with a "watch" command (not super critical)
