### ISSUE TITLE
Blueprint rendering fails with relative paths

### ISSUE THREAD

**Issue by reshnm** [gardener/landscapercli#87]
**What happened**:

Rendering a blueprint fails with relative paths.

**What you expected to happen**:

Rendering a blueprint should work when passing relative paths in command line flags.

**How to reproduce it (as minimally and precisely as possible)**:

This fails:

```
$ landscaper-cli blueprints render ./blueprint -c component/component-descriptor.yaml -f ./import-values.yaml
unable to read values file './import-values.yaml': file does not exist
```

This works:

```
$ landscaper-cli blueprints render ${PWD}/blueprints/virtual-landscaper -c ${PWD}/component/component-descriptor.yaml -f ${PWD}/import-values.yaml
```

**Anything else we need to know**:

This seems to be a regression. It was working with landscaper-cli version _v0.7.0_
After updating to version _v0.8.0_ it fails.

**Environment**:

```
$ landscaper-cli version

Landscaper-CLI Version: v0.8.0-42d97d8e47c1fd15d25541d42eacbc5fb1aeb38d
  GitCommit: 42d97d8e47c1fd15d25541d42eacbc5fb1aeb38d
  GitTreeState: dirty
  GoVersion: go1.16.5
  Compiler: gc
  Platform: darwin/amd64

Compatible Landscaper Version: v0.11.2
Compatible and included Component-Cli Version: v0.28.0
```

**Comment by achimweigel** [comment]
I will have a look on that
